version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npx expo build:web

artifacts:
  files:
    - "**/*"
  base-directory: client/web-build
